# Generated by Django 3.0.6 on 2020-05-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200522_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Dog')),
            ],
        ),
    ]
