# Generated by Django 3.0.6 on 2020-05-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=300, null=True)),
                ('protein', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('ash', models.FloatField(null=True)),
                ('fiber', models.FloatField(null=True)),
                ('moist', models.FloatField(null=True)),
                ('phosphorus', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('calory', models.FloatField(null=True)),
            ],
        ),
    ]
