# Generated by Django 3.0.6 on 2020-06-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200522_1104'),
        ('health', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkingStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
        migrations.CreateModel(
            name='WalkingEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now=True)),
                ('walking_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.WalkingStart')),
            ],
        ),
        migrations.CreateModel(
            name='WalkingActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField()),
                ('walking_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.WalkingStart')),
            ],
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('datetime', models.DateField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
    ]
