# Generated by Django 3.0.6 on 2020-06-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_activity_gps_walkingactive_walkingend_walkingstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gps',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='walkingend',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='walkingstart',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
