# Generated by Django 3.0.6 on 2020-06-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200605_2154'),
        ('health', '0004_auto_20200605_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkingstart',
            name='device',
        ),
        migrations.AddField(
            model_name='walkingactive',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walkingend',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walkingstart',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Dog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gps',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walkingend',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='walkingstart',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
