# Generated by Django 3.0.6 on 2020-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20200605_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkingend',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
