# Generated by Django 3.0.6 on 2020-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20200605_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doginfo',
            name='height',
        ),
        migrations.AddField(
            model_name='doginfo',
            name='snack_cnt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='walk_distance',
            field=models.IntegerField(null=True),
        ),
    ]
