# Generated by Django 3.0.6 on 2020-06-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20200607_1835'),
        ('health', '0007_auto_20200607_2255'),
    ]

    operations = [
    ]
