# Generated by Django 3.0.6 on 2020-06-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20200608_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
