# Generated by Django 3.0.6 on 2020-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200520_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='maxheight',
            new_name='max_height',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='maxweight',
            new_name='max_weight',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='minheight',
            new_name='min_height',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='minweight',
            new_name='min_weight',
        ),
        migrations.AddField(
            model_name='breed',
            name='group',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breed',
            name='origin',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
