# Generated by Django 3.0.6 on 2020-05-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200520_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='dogs',
            field=models.ManyToManyField(related_name='owners', to='accounts.Dog'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.Device'),
        ),
    ]
