# Generated by Django 3.0.6 on 2020-06-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200522_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='neutralization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
