version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=pupfit
      - MYSQL_USER=root
      - MYSQL_PASSWORD=hongsi
      - MYSQL_ROOT_PASSWORD=hongsi
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
  django:
    build: .
    environment:
      - DJANGO_DEBUG=True
    expose:
      - 8000
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app
    command:
      - bash
      - -c
      - |
        pip install -r requirements.txt
        ./wait-for-it.sh db:3306 -t 20
        python manage.py migrate
        python manage.py loaddata data/breeds.json data/foods.json
        chmod 111 ./wait-for-it.sh
        gunicorn pupfit.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - django